"""Generate engine-core function records (analysis/core_functions.tsv + docs/core-functions.md).

For every function in analysis/symbols.tsv (kind=func) this computes, from the binary:
  callers      direct jal sites
  vslots       vtables (analysis/vtables.tsv) that contain the function, with slot number
  callees      direct jal targets inside the body
  globals      .data/.bss addresses read/written (lui-pair resolved, vtables/strings excluded)
  strings      string literals referenced
and joins the recorded evidence/confidence (symbols.tsv) and signature (sigs.tsv).
Function bounds come from the latest export's functions.tsv.
"""
import collections
import csv
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from eedis import Image, resolve_pairs, func_end  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PASS = os.environ.get("GOW2_EXPORT", "pass4")
WRITES = {"sw", "sh", "sb", "sd", "sq", "swc1"}


def load_tsv(p):
    return list(csv.DictReader(open(p, encoding="utf-8-sig"), delimiter="\t"))


def main():
    img = Image()
    funcs = {int(r["addr"], 16): r for r in load_tsv(os.path.join(ROOT, "analysis", "exports", PASS, "functions.tsv"))}
    syms = []
    for line in open(os.path.join(ROOT, "analysis", "symbols.tsv")):
        if line.strip() and not line.startswith("#"):
            c = line.rstrip("\n").split("\t")
            if c[1] == "func":
                syms.append((int(c[0], 16), c[2], c[3], c[4] if len(c) > 4 else ""))
    sigs = {}
    for line in open(os.path.join(ROOT, "analysis", "sigs.tsv")):
        if line.strip() and not line.startswith("#"):
            c = line.rstrip("\n").split("\t")
            sigs[int(c[0], 16)] = (c[1], c[2] if len(c) > 2 else "")
    vslots = collections.defaultdict(list)
    for r in load_tsv(os.path.join(ROOT, "analysis", "vtables.tsv")):
        for i, fn in enumerate(r["slot_fns"].split(",")):
            if fn:
                vslots[int(fn, 16)].append(f"{r['vtable']}[{i + 1}]")
    vt_addrs = {int(r["vtable"], 16) for r in load_tsv(os.path.join(ROOT, "analysis", "vtables.tsv"))}
    names = {a: n for a, n, _, _ in syms}
    for line in open(os.path.join(ROOT, "analysis", "symbols.tsv")):
        if line.strip() and not line.startswith("#"):
            c = line.rstrip("\n").split("\t")
            if c[1] == "data":
                names[int(c[0], 16)] = c[2]
    names.update({a: r["name"] for a, r in funcs.items() if a not in names})

    callers = collections.defaultdict(list)
    lo, hi = img.text
    for a in range(lo, hi, 4):
        w = img.word(a)
        if w >> 26 == 0x03:
            callers[((a + 4) & 0xF0000000) | ((w & 0x3FFFFFF) << 2)].append(a)

    data_lo = img.sections[".data"][0]
    bss_hi = img.sections[".bss"][1]
    rows = []
    for a, name, conf, ev in syms:
        size = int(funcs[a]["size"]) if a in funcs else func_end(img, a) - a
        callees, reads, writes, strs = [], set(), set(), []
        for x, w, m, ops, res in resolve_pairs(img, a, a + size):
            if m == "jal":
                t = ((x + 4) & 0xF0000000) | ((w & 0x3FFFFFF) << 2)
                if t not in callees:
                    callees.append(t)
            elif res is not None:
                s = img.cstr(res)
                if s and len(s) > 2:
                    if s not in strs:
                        strs.append(s)
                elif data_lo <= res < bss_hi and res not in vt_addrs:
                    (writes if m in WRITES else reads).add(res)
        lab = lambda v: names.get(v, f"0x{v:08x}")
        sig = sigs.get(a)
        rows.append({
            "addr": f"{a:08x}", "name": name, "confidence": conf.upper(), "size": size,
            "signature": f"{sig[0]} {name}({sig[1]})" if sig else "",
            "callers": ", ".join(f"{lab(c)}" for c in sorted({img_func(funcs, c) for c in callers.get(a, [])} - {None})),
            "caller_sites": len(callers.get(a, [])),
            "vtable_slots": ", ".join(vslots.get(a, [])),
            "callees": ", ".join(lab(c) for c in callees),
            "globals_written": ", ".join(lab(g) for g in sorted(writes)),
            "globals_read": ", ".join(lab(g) for g in sorted(reads - writes)),
            "strings": " | ".join(strs[:8]),
            "evidence": ev,
        })
    out = os.path.join(ROOT, "analysis", "core_functions.tsv")
    with open(out, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()), delimiter="\t")
        w.writeheader()
        w.writerows(rows)
    md = [f"# Engine-core function records\n",
          f"Generated by `tools/core_report.py` from the binary + `analysis/symbols.tsv` (export `{PASS}`). "
          "Callers/callees/globals are computed from the code; *evidence* and *confidence* are the recorded "
          "reverse-engineering judgement. Functions reached only through vtables show 0 caller sites: "
          "see the `vtable slots` field.\n"]
    for r in rows:
        md.append(f"## `{r['addr']}` {r['name']}  - {r['confidence']}\n")
        md.append("| field | value |\n|---|---|")
        for k in ("signature", "size", "caller_sites", "callers", "vtable_slots", "callees", "globals_written",
                  "globals_read", "strings", "evidence"):
            v = str(r[k]).replace("|", "\\|") or "-"
            md.append(f"| {k.replace('_', ' ')} | {v} |")
        md.append("")
    open(os.path.join(ROOT, "docs", "core-functions.md"), "w", encoding="utf-8").write("\n".join(md))
    print(f"{len(rows)} records -> {out}, docs/core-functions.md")


def img_func(funcs, site):
    starts = img_func.starts = getattr(img_func, "starts", None) or sorted(funcs)
    import bisect
    i = bisect.bisect_right(starts, site) - 1
    if i < 0:
        return None
    s = starts[i]
    return s if site < s + int(funcs[s]["size"]) + 8 else None


if __name__ == "__main__":
    main()
